### ISSUE TITLE
Hanging signs cause ClassCastException and do not drop with text

### ISSUE THREAD

**Issue by logitechno** [joshuaprince/SilkSigns#1] opened 2024-07-23 19:01 UTC
When splitting a hanging sign, this error is displayed. The text is not saved
Core: purpur
Version: 1.21
https://mclo.gs/L3C2iHJ

**Comment by joshuaprince** [comment] 2024-07-24 04:53
Confirmed on latest builds of Spigot, Paper, and Purpur.

This is caused by a bug in Spigot which was added with the item meta changes on 2024-07-06. I filed [SPIGOT-7846](https://hub.spigotmc.org/jira/browse/SPIGOT-7846) since it needs to be fixed there before the error here can be fixed. I don't see any easy workaround for SilkSigns until then. Until it's fixed in Spigot, Paper versions 89 and below (Purpur versions 2267 and below) should be unaffected.

**Comment by joshuaprince** [comment] 2024-07-25 01:35
The underlying bug is now fixed in the latest Spigot builds, but since the plugin is for Paper+ only, the fix has to propagate downstream. https://github.com/PaperMC/Paper/issues/11160

**Comment by joshuaprince** [comment] 2024-08-14 01:29
Fixed in all 1.21.1 server builds, as well as:
- Paper 1.21 build 128+
- Purpur 1.21 build 2282+

Upgrade your server if you're seeing the error with hanging signs.

**Closed as completed by joshuaprince** 2024-08-14 01:29 UTC
